export type LandingLocale = "en" | "ar" | "fr";

export const landingCopy = {
  en: {
    brandName: "Waqto Salat",
    logoAlt: "Waqto Salat logo",
    navigation: {
      ariaLabel: "Primary navigation",
      learn: "Learn",
      allGuides: "All Salah Guides",
      features: "Features",
      about: "About",
      faq: "FAQ",
      languageLabel: "View this page in Arabic",
      languageName: "العربية",
      languageShort: "AR",
      getApp: "Get App",
      download: "Download",
    },
    hero: {
      titleStart: "Prayer reminders that move with the",
      titleAccent: "salah time",
      body: "Set reminders before or after Fajr, Dhuhr, Asr, Maghrib, or Isha once. Waqto Salat updates them automatically every day as prayer times change.",
      cards: [
        { title: "Dynamic salah reminders", body: "Before or after each prayer" },
        { title: "No ads. Qibla included.", body: "Clean design for daily salah" },
      ],
      reminderCta: "See how reminders work",
      promise: "100% Free · No Subscription · No Ads",
    },
    reminders: {
      eyebrow: "Dynamic salah reminders",
      title: "Prayer times change. Your reminders should too.",
      body: "A fixed alarm does not follow Fajr, Maghrib, or the changing salah schedule. Waqto Salat lets you create reminders around prayer times, so your routine stays connected to salah every day.",
      stepLabel: "Step",
      steps: [
        { title: "Choose a prayer", body: "Fajr, Dhuhr, Asr, Maghrib, or Isha." },
        { title: "Set before or after", body: "Create a reminder around the salah time once." },
        { title: "Let it move daily", body: "Waqto Salat updates the reminder as prayer times shift." },
      ],
      useCases: [
        "Wake up 20 minutes before Fajr",
        "Pray 10 minutes after Dhuhr during work",
        "Get ready before Maghrib while commuting",
      ],
    },
    values: {
      title: "Built around your daily salah",
      body: "A focused Android prayer app for reminders, prayer times, Qibla direction, widgets, and calm daily use.",
      items: [
        { title: "100% Ad-Free & Free", body: "No ads or premium subscriptions. The in-app support button is optional and never required." },
        { title: "Dynamic Salah Reminders", body: "Set reminders before or after any prayer time and let them move with the daily salah schedule." },
        { title: "Qibla Direction", body: "Accurate, clean compass to help you establish the correct direction anywhere." },
        { title: "Home Widgets", body: "Keep track of upcoming prayers beautifully directly on your home screen." },
        { title: "Multi-language", body: "Designed for a global ummah with support for multiple languages out of the box." },
      ],
      closingTitle: "Made with Ihsan",
      closingBody: "Beautiful design meets exact calculation method formulas for worldwide accuracy.",
    },
    features: [
      {
        title: "Accurate Prayer Times",
        body: "Uses recognized calculation methods with location, timezone, and calibration controls so you can align prayer times with your community when needed.",
        alt: "Waqto Salat Android app showing prayer times and reminder settings",
      },
      {
        title: "Minimalist Qibla Compass",
        body: "Finding the direction of the Kaaba should be straightforward. Our compass is designed to be highly legible and completely free of clutter.",
        alt: "Waqto Salat Android app showing minimalist Qibla compass direction",
      },
      {
        title: "Glanceable Widgets",
        body: "Keep tracking your next prayer right on your home screen or lock screen with beautifully crafted and distraction-free widgets.",
        alt: "Waqto Salat Android home screen widget showing upcoming prayer time",
      },
      {
        title: "Calm By Design",
        body: "No loud animations. No stressful red text. Just deep greens, warm gold, and a layout that breathes. Designed to lower your heart rate, not raise it.",
        alt: "Waqto Salat Android app calm prayer dashboard design",
      },
    ],
    about: {
      eyebrow: "About Waqto Salat",
      title: "A clear focus on Salah.",
      body: "Built to help Muslims organize their day around salah with reminders that move as prayer times change.",
      cards: [
        { title: "Privacy first", body: "Published Play Store data safety details state that Waqto Salat does not collect data or share data with third parties." },
        { title: "Prayer-based reminders", body: "Set reminders before or after salah times once, then let them follow the daily prayer schedule." },
        { title: "Free forever", body: "No ads, subscriptions, or locked prayer essentials. Supporting development inside the app is always optional." },
      ],
    },
    support: {
      appLabel: "Android prayer companion",
      title: "Make your day revolve around salah, not fixed alarms.",
      body: "Download Waqto Salat for dynamic salah reminders, accurate prayer times, Qibla direction, and home widgets in a focused Android app with no ads and no subscription.",
      contactSupport: "Contact support",
      prayerTitle: "Built around the five daily prayers",
      prayerBody: "The interface follows the rhythm of Fajr, Dhuhr, Asr, Maghrib, and Isha so the next prayer is always easy to see.",
      prayerNames: ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"],
      legalLabel: "Legal",
      legalTitle: "Privacy, terms, and feedback in plain language.",
      privacyTitle: "Privacy Policy",
      privacyBody: "Waqto Salat is designed for prayer utility, not tracking. The published Google Play data safety details state that the app does not collect data or share data with third parties.",
      privacyLink: "Read privacy policy",
      termsTitle: "Terms of Service",
      termsBody: "Prayer time calculations can vary by method, location, device settings, and local authority guidance. Use the app as a practical companion and adjust settings for your community.",
      termsLink: "Read terms",
      contactTitle: "Contact / Feedback",
      contactBody: "Send app support questions, correction requests, or feedback about prayer time settings.",
      openGmail: "Open in Gmail",
      supportTopics: [
        "Prayer time or calculation feedback",
        "Bug reports and Android device issues",
        "Corrections for website content",
      ],
      freeTitle: "Free Forever",
      freeBody: "Waqto Salat has no ads, subscriptions, or locked prayer essentials. The app includes an optional support button for anyone who chooses to support its development; using it is never required.",
    },
    faq: {
      label: "Questions",
      title: "Answers before you download.",
      body: "Quick details about pricing, ads, privacy, prayer time accuracy, and the features included in Waqto Salat.",
      items: [
        { question: "Is Waqto Salat free?", answer: "Yes. Waqto Salat is free to download and use, with no ads or premium subscriptions. An optional in-app support button is available for anyone who chooses to support development, but it is never required and does not unlock prayer features." },
        { question: "Does Waqto Salat show ads?", answer: "No. Waqto Salat is designed as an ad-free prayer companion for Android." },
        { question: "What features does Waqto Salat include?", answer: "Waqto Salat includes prayer times, dynamic salah reminders, Qibla direction, home screen widgets, per-prayer calibration, and multilingual support." },
        { question: "Can I set reminders before prayer time?", answer: "Yes. Waqto Salat lets you create reminders before salah times so you can prepare for Fajr, Dhuhr, Asr, Maghrib, or Isha." },
        { question: "Can I set reminders after prayer time?", answer: "Yes. You can use reminders after a prayer time too, which is helpful for work, commuting, or building a consistent salah routine." },
        { question: "Do reminders update when prayer times change?", answer: "Yes. Dynamic salah reminders stay tied to the selected prayer time and move as daily prayer times shift." },
        { question: "How accurate are the prayer times?", answer: "Prayer times depend on location, timezone, calculation method, and local guidance. Waqto Salat gives you practical settings and calibration so you can align the app with your community." },
        { question: "Does Waqto Salat collect my data?", answer: "The published Google Play data safety details state that Waqto Salat does not collect data or share data with third parties." },
      ],
    },
    learn: {
      label: "Learn",
      title: "Learn the prayers that shape Muslim life.",
      body: "A focused Salah library covering obligatory, Sunnah, voluntary, and special prayers in practical guides.",
      viewAll: "View all guides",
      guides: [
        { title: "Five Daily Prayers", href: "/learn/five-daily-prayers/", summary: "Fajr, Dhuhr, Asr, Maghrib, and Isha." },
        { title: "Istikhara Prayer", href: "/learn/istikhara-prayer/", summary: "Guidance, du'a, dreams, and signs." },
        { title: "Sunnah Prayers", href: "/learn/sunnah-prayers/", summary: "Emphasized and non-emphasized Sunnah." },
        { title: "Witr Prayer", href: "/learn/witr-prayer/", summary: "Odd rak'ahs after Isha and before Fajr." },
        { title: "Nafl Prayers", href: "/learn/nafl-prayers/", summary: "Voluntary prayers beyond required salah." },
        { title: "Duha Prayer", href: "/learn/duha-prayer/", summary: "Forenoon prayer after sunrise." },
        { title: "Tahajjud Prayer", href: "/learn/tahajjud-prayer/", summary: "Night prayer before Fajr." },
        { title: "Eid al-Fitr and Eid al-Adha", href: "/learn/eid-al-fitr-and-eid-al-adha-prayer/", summary: "Eid timing, takbirs, and khutbah." },
        { title: "Janazah Prayer", href: "/learn/janazah-prayer/", summary: "The Muslim funeral prayer." },
        { title: "Eclipse Prayer", href: "/learn/eclipse-prayer/", summary: "Solar and lunar eclipse salah." },
        { title: "Taraweeh Prayer", href: "/learn/taraweeh-prayer/", summary: "Ramadan night prayer and Witr." },
      ],
    },
    resources: {
      label: "Prayer app resources",
      title: "Clear answers for choosing a prayer times app.",
      items: [
        { href: "/ad-free-prayer-times-app/", title: "Ad-free prayer times app", body: "Why Waqto Salat keeps the prayer experience quiet, focused, and free from ads." },
        { href: "/salah-reminder-app/", title: "Salah reminder app", body: "How reminders help you plan the day around each prayer without extra noise." },
        { href: "/qibla-compass-app/", title: "Qibla compass app", body: "A clean Qibla direction experience for Android with minimal visual clutter." },
        { href: "/prayer-times-widget-android/", title: "Prayer times widget", body: "Glanceable Android widgets for checking the next salah from the home screen." },
        { href: "/how-prayer-times-are-calculated/", title: "Prayer time calculation", body: "A plain-language guide to location, methods, timezones, and calibration." },
      ],
    },
    footer: {
      body: "Built to help Muslims organize their day around salah without distractions, ads, or locked features.",
      seoBody: "Waqto Salat is a focused Muslim prayer times app, salah reminder app, and Qibla compass app for Android.",
      application: "Application",
      features: "Features",
      about: "About Us",
      faq: "FAQ",
      download: "Download for Android",
      learn: "Learn",
      learnAbout: "Learn about Salah",
      resources: "Resources",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      methodology: "Editorial Methodology",
      contact: "Contact / Feedback",
      copyright: "Waqto Salat. All rights reserved.",
      closing: "Waqto Salat is completely free. Its in-app support button is optional and never required.",
    },
  },
  fr: {
    brandName: "Waqto Salat",
    logoAlt: "Logo Waqto Salat",
    navigation: {
      ariaLabel: "Navigation principale",
      learn: "Apprendre",
      allGuides: "Tous les guides de prière",
      features: "Fonctionnalités",
      about: "À propos",
      faq: "FAQ",
      languageLabel: "Choisir une autre langue",
      languageName: "Français",
      languageShort: "FR",
      getApp: "Obtenir",
      download: "Télécharger",
    },
    hero: {
      titleStart: "Des rappels qui suivent l'heure de la",
      titleAccent: "prière",
      body: "Réglez une fois un rappel avant ou après Fajr, Dhuhr, Asr, Maghrib ou Isha. Waqto Salat le met automatiquement à jour chaque jour lorsque les horaires changent.",
      cards: [
        { title: "Rappels de prière dynamiques", body: "Avant ou après chaque prière" },
        { title: "Sans publicité, Qibla incluse", body: "Une interface apaisée pour la salat" },
      ],
      reminderCta: "Voir le fonctionnement des rappels",
      promise: "100 % gratuit · Sans abonnement · Sans publicité",
    },
    reminders: {
      eyebrow: "Rappels de prière dynamiques",
      title: "Les horaires changent. Vos rappels aussi.",
      body: "Une alarme fixe ne suit ni Fajr, ni Maghrib, ni l'évolution quotidienne des horaires. Waqto Salat vous permet de créer des rappels liés aux prières pour garder votre journée organisée autour de la salat.",
      stepLabel: "Étape",
      steps: [
        { title: "Choisissez une prière", body: "Fajr, Dhuhr, Asr, Maghrib ou Isha." },
        { title: "Réglez avant ou après", body: "Créez une fois un rappel autour de l'heure de prière." },
        { title: "Laissez-le s'adapter", body: "Waqto Salat actualise le rappel quand l'horaire change." },
      ],
      useCases: [
        "Se réveiller 20 minutes avant Fajr",
        "Prier 10 minutes après Dhuhr pendant le travail",
        "Se préparer avant Maghrib sur le trajet du retour",
      ],
    },
    values: {
      title: "Conçu autour de votre salat quotidienne",
      body: "Une application Android ciblée pour les rappels, les horaires de prière, la Qibla, les widgets et une utilisation quotidienne apaisée.",
      items: [
        { title: "Gratuit et sans publicité", body: "Aucune publicité ni abonnement premium. Le bouton de soutien intégré est facultatif et jamais nécessaire." },
        { title: "Rappels de salat dynamiques", body: "Programmez un rappel avant ou après une prière et laissez-le suivre les horaires quotidiens." },
        { title: "Direction de la Qibla", body: "Une boussole précise et épurée pour trouver la bonne direction où que vous soyez." },
        { title: "Widgets d'accueil", body: "Consultez élégamment la prochaine prière depuis votre écran d'accueil." },
        { title: "Multilingue", body: "Pensé pour une oumma mondiale, avec plusieurs langues disponibles." },
      ],
      closingTitle: "Réalisé avec ihsan",
      closingBody: "Un design soigné associé à des méthodes de calcul reconnues pour une utilisation partout dans le monde.",
    },
    features: [
      {
        title: "Horaires de prière précis",
        body: "Utilise des méthodes de calcul reconnues avec la localisation, le fuseau horaire et des réglages d'ajustement pour s'aligner sur votre communauté.",
        alt: "Application Android Waqto Salat affichant les horaires de prière et les réglages de rappel",
      },
      {
        title: "Boussole Qibla minimaliste",
        body: "Trouver la direction de la Kaaba doit rester simple. La boussole est lisible, précise et sans encombrement visuel.",
        alt: "Application Waqto Salat affichant une boussole Qibla minimaliste",
      },
      {
        title: "Widgets lisibles d'un coup d'œil",
        body: "Suivez la prochaine prière sur l'écran d'accueil ou l'écran verrouillé grâce à des widgets sobres et clairs.",
        alt: "Widget Android Waqto Salat affichant l'heure de la prochaine prière",
      },
      {
        title: "Une conception apaisée",
        body: "Pas d'animations bruyantes ni de texte alarmant. Des verts profonds, un or chaleureux et une mise en page qui respire.",
        alt: "Tableau de bord apaisé de l'application Android Waqto Salat",
      },
    ],
    about: {
      eyebrow: "À propos de Waqto Salat",
      title: "La salat, avec clarté.",
      body: "Conçu pour aider les musulmans à organiser leur journée autour de rappels qui évoluent avec les horaires de prière.",
      cards: [
        { title: "La confidentialité d'abord", body: "La fiche de sécurité des données publiée sur Google Play indique que Waqto Salat ne collecte ni ne partage de données avec des tiers." },
        { title: "Rappels liés aux prières", body: "Réglez une fois des rappels avant ou après la salat, puis laissez-les suivre les horaires quotidiens." },
        { title: "Toujours gratuit", body: "Aucune publicité, aucun abonnement et aucune fonction essentielle verrouillée. Le soutien au développement reste facultatif." },
      ],
    },
    support: {
      appLabel: "Compagnon de prière Android",
      title: "Organisez votre journée autour de la salat, pas d'alarmes fixes.",
      body: "Téléchargez Waqto Salat pour ses rappels dynamiques, ses horaires de prière, la direction de la Qibla et ses widgets, sans publicité ni abonnement.",
      contactSupport: "Contacter l'assistance",
      prayerTitle: "Conçu autour des cinq prières quotidiennes",
      prayerBody: "L'interface suit le rythme de Fajr, Dhuhr, Asr, Maghrib et Isha afin que la prochaine prière reste toujours visible.",
      prayerNames: ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"],
      legalLabel: "Informations légales",
      legalTitle: "Confidentialité, conditions et retours en langage clair.",
      privacyTitle: "Politique de confidentialité",
      privacyBody: "Waqto Salat est conçu comme un outil de prière, pas comme un outil de suivi. La fiche Google Play indique que l'application ne collecte ni ne partage de données avec des tiers.",
      privacyLink: "Lire la politique de confidentialité",
      termsTitle: "Conditions d'utilisation",
      termsBody: "Les horaires peuvent varier selon la méthode, le lieu, les réglages de l'appareil et les recommandations locales. Ajustez l'application selon votre communauté.",
      termsLink: "Lire les conditions",
      contactTitle: "Contact et commentaires",
      contactBody: "Envoyez vos questions d'assistance, demandes de correction ou remarques sur les réglages des horaires de prière.",
      openGmail: "Ouvrir dans Gmail",
      supportTopics: [
        "Commentaires sur les horaires ou leur calcul",
        "Signalement de bugs et problèmes Android",
        "Corrections du contenu du site",
      ],
      freeTitle: "Toujours gratuit",
      freeBody: "Waqto Salat ne contient ni publicité, ni abonnement, ni fonction de prière verrouillée. Un bouton de soutien facultatif permet d'aider le développement, sans aucune obligation.",
    },
    faq: {
      label: "Questions",
      title: "Les réponses avant de télécharger.",
      body: "L'essentiel sur le prix, les publicités, la confidentialité, la précision des horaires et les fonctions de Waqto Salat.",
      items: [
        { question: "Waqto Salat est-il gratuit ?", answer: "Oui. Waqto Salat est gratuit, sans publicité ni abonnement premium. Le bouton de soutien intégré est facultatif et ne débloque aucune fonction de prière." },
        { question: "Waqto Salat affiche-t-il des publicités ?", answer: "Non. Waqto Salat est un compagnon de prière Android sans publicité." },
        { question: "Quelles fonctions sont incluses ?", answer: "Horaires de prière, rappels dynamiques, direction de la Qibla, widgets, ajustement par prière et prise en charge de plusieurs langues." },
        { question: "Puis-je recevoir un rappel avant la prière ?", answer: "Oui. Vous pouvez créer un rappel avant Fajr, Dhuhr, Asr, Maghrib ou Isha pour vous préparer." },
        { question: "Puis-je recevoir un rappel après la prière ?", answer: "Oui. Les rappels après l'heure peuvent être utiles au travail, en déplacement ou pour consolider une routine." },
        { question: "Les rappels suivent-ils les changements d'horaires ?", answer: "Oui. Ils restent liés à la prière choisie et se déplacent avec les horaires quotidiens." },
        { question: "Les horaires de prière sont-ils précis ?", answer: "Ils dépendent du lieu, du fuseau horaire, de la méthode de calcul et des recommandations locales. Les réglages permettent de les aligner sur votre communauté." },
        { question: "Waqto Salat collecte-t-il mes données ?", answer: "La fiche de sécurité des données publiée sur Google Play indique que Waqto Salat ne collecte ni ne partage de données avec des tiers." },
      ],
    },
    learn: {
      label: "Apprendre",
      title: "Comprendre les prières qui rythment la vie musulmane.",
      body: "Une bibliothèque dédiée à la salat, avec des guides pratiques sur les prières obligatoires et particulières.",
      viewAll: "Voir tous les guides",
      guides: [
        { title: "Les cinq prières quotidiennes", href: "/fr/learn/five-daily-prayers/", summary: "Fajr, Dhuhr, Asr, Maghrib et Isha." },
        { title: "La prière d'Istikhara", href: "/fr/learn/istikhara-prayer/", summary: "Guidance, invocation, consultation et confiance." },
        { title: "Les prières Sunnah", href: "/fr/learn/sunnah-prayers/", summary: "Rawatib et prières liées à la pratique prophétique." },
        { title: "La prière du Witr", href: "/fr/learn/witr-prayer/", summary: "Prière impaire après Isha et avant Fajr." },
        { title: "Les prières Nafl", href: "/fr/learn/nafl-prayers/", summary: "Prières volontaires au-delà de la salat obligatoire." },
        { title: "La prière de Duha", href: "/fr/learn/duha-prayer/", summary: "Prière volontaire de la matinée." },
        { title: "La prière de Tahajjud", href: "/fr/learn/tahajjud-prayer/", summary: "Prière nocturne volontaire avant Fajr." },
        { title: "Aïd al-Fitr et Aïd al-Adha", href: "/fr/learn/eid-al-fitr-and-eid-al-adha-prayer/", summary: "La prière, les takbirs et les deux fêtes." },
        { title: "La prière Janazah", href: "/fr/learn/janazah-prayer/", summary: "Prière funéraire et invocations pour le défunt." },
        { title: "La prière de l'éclipse", href: "/fr/learn/eclipse-prayer/", summary: "Salat pendant une éclipse solaire ou lunaire." },
        { title: "La prière de Taraweeh", href: "/fr/learn/taraweeh-prayer/", summary: "Prière nocturne de Ramadan et Witr." },
      ],
    },
    resources: {
      label: "Ressources sur l'application",
      title: "Des réponses claires pour choisir une application de prière.",
      items: [
        { href: "/fr/ad-free-prayer-times-app/", title: "Application sans publicité", body: "Pourquoi Waqto Salat garde l'expérience de prière calme et sans publicité." },
        { href: "/fr/salah-reminder-app/", title: "Rappels de salat", body: "Comment les rappels aident à organiser la journée autour de chaque prière." },
        { href: "/fr/qibla-compass-app/", title: "Boussole Qibla", body: "Une direction de la Qibla claire sur Android, sans encombrement." },
        { href: "/fr/prayer-times-widget-android/", title: "Widget d'horaires", body: "Consultez la prochaine salat directement depuis l'écran d'accueil." },
        { href: "/fr/how-prayer-times-are-calculated/", title: "Calcul des horaires", body: "Comprendre le lieu, les méthodes, les fuseaux horaires et les ajustements." },
      ],
    },
    footer: {
      body: "Conçu pour aider les musulmans à organiser leur journée autour de la salat, sans distraction, publicité ni fonction verrouillée.",
      seoBody: "Waqto Salat est une application Android d'horaires de prière, de rappels de salat et de direction de la Qibla.",
      application: "Application",
      features: "Fonctionnalités",
      about: "À propos",
      faq: "FAQ",
      download: "Télécharger pour Android",
      learn: "Apprendre",
      learnAbout: "Apprendre la salat",
      resources: "Ressources",
      legal: "Mentions légales",
      privacy: "Politique de confidentialité",
      terms: "Conditions d'utilisation",
      methodology: "Méthodologie éditoriale",
      contact: "Contact et commentaires",
      copyright: "Waqto Salat. Tous droits réservés.",
      closing: "Waqto Salat est entièrement gratuit. Le bouton de soutien intégré est facultatif et jamais requis.",
    },
  },
  ar: {
    brandName: "وقت الصلاة",
    logoAlt: "شعار وقت الصلاة",
    navigation: {
      ariaLabel: "التنقل الرئيسي",
      learn: "تعلّم",
      allGuides: "كل أدلة الصلاة",
      features: "المزايا",
      about: "عن التطبيق",
      faq: "الأسئلة",
      languageLabel: "عرض هذه الصفحة باللغة الإنجليزية",
      languageName: "English",
      languageShort: "EN",
      getApp: "حمّل التطبيق",
      download: "حمّل التطبيق",
    },
    hero: {
      titleStart: "تذكيرات للصلاة تتغير تلقائيا مع",
      titleAccent: "وقت الصلاة",
      body: "اضبط تذكيرا قبل الفجر أو الظهر أو العصر أو المغرب أو العشاء، أو بعدها، مرة واحدة. يحدّث وقت الصلاة موعده تلقائيا كل يوم مع تغير مواقيت الصلاة.",
      cards: [
        { title: "تذكيرات صلاة متحركة", body: "قبل كل صلاة أو بعدها" },
        { title: "بلا إعلانات، والقبلة مدمجة", body: "تصميم هادئ للصلاة اليومية" },
      ],
      reminderCta: "شاهد كيف تعمل التذكيرات",
      promise: "مجاني بالكامل · بلا اشتراك · بلا إعلانات",
    },
    reminders: {
      eyebrow: "تذكيرات صلاة متحركة",
      title: "تتغير مواقيت الصلاة، وكذلك ينبغي لتذكيراتك.",
      body: "لا يتبع المنبّه الثابت وقت الفجر أو المغرب ولا تغيّر جدول الصلاة. يتيح لك وقت الصلاة إنشاء تذكيرات مرتبطة بالمواقيت لتبقى عاداتك اليومية متصلة بالصلاة.",
      stepLabel: "الخطوة",
      steps: [
        { title: "اختر الصلاة", body: "الفجر أو الظهر أو العصر أو المغرب أو العشاء." },
        { title: "حدد قبلها أو بعدها", body: "أنشئ تذكيرا مرتبطا بوقت الصلاة مرة واحدة." },
        { title: "دعه يتغير يوميا", body: "يحدّث وقت الصلاة التذكير كلما تغير موعد الصلاة." },
      ],
      useCases: [
        "استيقظ قبل الفجر بعشرين دقيقة",
        "صلّ الظهر بعد موعده بعشر دقائق أثناء العمل",
        "استعد للمغرب أثناء العودة إلى المنزل",
      ],
    },
    values: {
      title: "مصمم حول صلاتك اليومية",
      body: "تطبيق أندرويد مركز للتذكيرات ومواقيت الصلاة واتجاه القبلة والويدجت والاستخدام اليومي الهادئ.",
      items: [
        { title: "مجاني وبلا إعلانات", body: "لا إعلانات ولا اشتراكات مدفوعة. زر الدعم داخل التطبيق اختياري ولا يلزم استخدامه." },
        { title: "تذكيرات صلاة متحركة", body: "اضبط تذكيرا قبل أي صلاة أو بعدها ودعه يتحرك مع الجدول اليومي." },
        { title: "اتجاه القبلة", body: "بوصلة دقيقة وواضحة تساعدك على معرفة الاتجاه أينما كنت." },
        { title: "ويدجت للشاشة", body: "تابع الصلاة القادمة بسهولة من شاشتك الرئيسية." },
        { title: "متعدد اللغات", body: "مصمم للمسلمين حول العالم مع دعم لغات متعددة." },
      ],
      closingTitle: "صنع بإحسان",
      closingBody: "يجمع التصميم الجميل بين طرق الحساب الدقيقة للوصول إلى مواقيت مناسبة حول العالم.",
    },
    features: [
      {
        title: "مواقيت صلاة دقيقة",
        body: "يستخدم طرق حساب معروفة مع إعدادات الموقع والمنطقة الزمنية والمعايرة لتتمكن من مواءمة المواقيت مع مجتمعك عند الحاجة.",
        alt: "تطبيق وقت الصلاة يعرض المواقيت وإعدادات التذكير",
      },
      {
        title: "بوصلة قبلة بسيطة",
        body: "يجب أن تكون معرفة اتجاه الكعبة واضحة ومباشرة، لذلك صممت البوصلة لتكون سهلة القراءة وخالية من الازدحام.",
        alt: "تطبيق وقت الصلاة يعرض اتجاه القبلة ببوصلة بسيطة",
      },
      {
        title: "ويدجت سريعة القراءة",
        body: "تابع الصلاة القادمة من الشاشة الرئيسية أو شاشة القفل عبر ويدجت جميلة وهادئة.",
        alt: "ويدجت وقت الصلاة على شاشة أندرويد تعرض موعد الصلاة القادمة",
      },
      {
        title: "هدوء في التصميم",
        body: "لا حركات صاخبة ولا ألوان مقلقة، بل أخضر عميق وذهبي دافئ ومساحات مريحة تساعدك على التركيز.",
        alt: "واجهة عربية هادئة لتطبيق وقت الصلاة على أندرويد",
      },
    ],
    about: {
      eyebrow: "عن وقت الصلاة",
      title: "تركيز واضح على الصلاة.",
      body: "صمم لمساعدة المسلمين على تنظيم يومهم حول الصلاة بتذكيرات تتحرك مع تغير المواقيت.",
      cards: [
        { title: "الخصوصية أولا", body: "تفيد بيانات الأمان المنشورة في Google Play بأن وقت الصلاة لا يجمع البيانات ولا يشاركها مع أطراف خارجية." },
        { title: "تذكيرات مرتبطة بالصلاة", body: "اضبط تذكيرا قبل وقت الصلاة أو بعدها مرة واحدة، ثم دعه يتبع الجدول اليومي." },
        { title: "مجاني دائما", body: "بلا إعلانات أو اشتراكات أو مزايا صلاة مقفلة. دعم التطوير من داخل التطبيق اختياري دائما." },
      ],
    },
    support: {
      appLabel: "رفيق الصلاة على أندرويد",
      title: "اجعل يومك يدور حول الصلاة، لا حول منبّهات ثابتة.",
      body: "حمّل وقت الصلاة لتحصل على تذكيرات متحركة ومواقيت دقيقة واتجاه القبلة وويدجت للشاشة في تطبيق أندرويد هادئ بلا إعلانات أو اشتراك.",
      contactSupport: "تواصل مع الدعم",
      prayerTitle: "مصمم حول الصلوات الخمس",
      prayerBody: "تتبع الواجهة إيقاع الفجر والظهر والعصر والمغرب والعشاء لتبقى الصلاة القادمة واضحة دائما.",
      prayerNames: ["الفجر", "الظهر", "العصر", "المغرب", "العشاء"],
      legalLabel: "القانوني",
      legalTitle: "الخصوصية والشروط والملاحظات بلغة واضحة.",
      privacyTitle: "سياسة الخصوصية",
      privacyBody: "صمم وقت الصلاة لخدمة الصلاة لا للتتبع. تفيد بيانات الأمان المنشورة في Google Play بأن التطبيق لا يجمع البيانات ولا يشاركها مع أطراف خارجية.",
      privacyLink: "اقرأ سياسة الخصوصية",
      termsTitle: "شروط الخدمة",
      termsBody: "قد تختلف مواقيت الصلاة بحسب طريقة الحساب والموقع وإعدادات الجهاز وتوجيه الجهة المحلية. استخدم التطبيق رفيقا عمليا واضبطه بما يناسب مجتمعك.",
      termsLink: "اقرأ الشروط",
      contactTitle: "التواصل والملاحظات",
      contactBody: "أرسل أسئلة الدعم أو طلبات التصحيح أو ملاحظاتك حول إعدادات مواقيت الصلاة.",
      openGmail: "افتح في Gmail",
      supportTopics: [
        "ملاحظات مواقيت الصلاة أو طرق الحساب",
        "بلاغات الأخطاء ومشكلات أجهزة أندرويد",
        "تصحيحات محتوى الموقع",
      ],
      freeTitle: "مجاني دائما",
      freeBody: "وقت الصلاة بلا إعلانات أو اشتراكات أو مزايا صلاة أساسية مقفلة. يتضمن التطبيق زر دعم اختياري لمن يرغب في دعم تطويره، ولا يلزم استخدامه.",
    },
    faq: {
      label: "الأسئلة الشائعة",
      title: "إجابات قبل التحميل.",
      body: "إجابات سريعة عن السعر والإعلانات والخصوصية ودقة المواقيت والمزايا الموجودة في وقت الصلاة.",
      items: [
        { question: "هل تطبيق وقت الصلاة مجاني؟", answer: "نعم. التطبيق مجاني للتنزيل والاستخدام، بلا إعلانات أو اشتراك مدفوع. يوجد داخله زر دعم اختياري لمن يرغب في دعم التطوير، لكنه غير مطلوب ولا يفتح مزايا صلاة محجوبة." },
        { question: "هل يعرض وقت الصلاة إعلانات؟", answer: "لا. صمم وقت الصلاة ليكون رفيقا هادئا للصلاة على أندرويد بلا إعلانات." },
        { question: "ما المزايا التي يقدمها وقت الصلاة؟", answer: "يشمل مواقيت الصلاة والتذكيرات المتحركة واتجاه القبلة وويدجت الشاشة الرئيسية ومعايرة كل صلاة ودعم لغات متعددة." },
        { question: "هل يمكن ضبط تذكير قبل الصلاة؟", answer: "نعم. يمكنك إنشاء تذكير قبل الفجر أو الظهر أو العصر أو المغرب أو العشاء لتستعد للصلاة." },
        { question: "هل يمكن ضبط تذكير بعد الصلاة؟", answer: "نعم. يمكنك استخدام تذكير بعد وقت الصلاة، وهو مفيد أثناء العمل أو التنقل أو لبناء عادة ثابتة." },
        { question: "هل تتغير التذكيرات مع تغير المواقيت؟", answer: "نعم. تبقى التذكيرات مرتبطة بالصلاة المحددة وتتحرك مع تغير مواقيتها اليومية." },
        { question: "ما مدى دقة مواقيت الصلاة؟", answer: "تعتمد المواقيت على الموقع والمنطقة الزمنية وطريقة الحساب والتوجيه المحلي. يوفر وقت الصلاة إعدادات ومعايرة لتوافق مجتمعك." },
        { question: "هل يجمع وقت الصلاة بياناتي؟", answer: "تفيد بيانات الأمان المنشورة في Google Play بأن وقت الصلاة لا يجمع البيانات ولا يشاركها مع أطراف خارجية." },
      ],
    },
    learn: {
      label: "تعلّم",
      title: "تعلّم الصلوات التي تشكّل حياة المسلم.",
      body: "مكتبة مركزة عن الصلاة تقدم أدلة عملية للصلوات المفروضة والسنن والنوافل والصلوات الخاصة.",
      viewAll: "تصفح كل الأدلة",
      guides: [
        { title: "الصلوات الخمس", href: "/ar/learn/five-daily-prayers/", summary: "الفجر والظهر والعصر والمغرب والعشاء." },
        { title: "صلوات السنة", href: "/ar/learn/sunnah-prayers/", summary: "السنن المؤكدة والرواتب حول الفرائض." },
        { title: "صلاة الوتر", href: "/ar/learn/witr-prayer/", summary: "صلاة فردية بعد العشاء وقبل الفجر." },
        { title: "صلوات النفل", href: "/ar/learn/nafl-prayers/", summary: "صلوات تطوعية زيادة على الفرائض." },
        { title: "صلاة الضحى", href: "/ar/learn/duha-prayer/", summary: "نافلة أول النهار بعد الشروق." },
        { title: "صلاة التهجد", href: "/ar/learn/tahajjud-prayer/", summary: "قيام الليل بعد العشاء وقبل الفجر." },
        { title: "صلاة الاستخارة", href: "/ar/learn/istikhara-prayer/", summary: "الدعاء والاستشارة والعمل والتوكل." },
        { title: "صلاة العيدين", href: "/ar/learn/eid-al-fitr-and-eid-al-adha-prayer/", summary: "عيد الفطر وعيد الأضحى." },
        { title: "صلاة الجنازة", href: "/ar/learn/janazah-prayer/", summary: "الصلاة على الميت المسلم." },
        { title: "صلاة الكسوف والخسوف", href: "/ar/learn/eclipse-prayer/", summary: "الصلاة عند كسوف الشمس أو خسوف القمر." },
        { title: "صلاة التراويح", href: "/ar/learn/taraweeh-prayer/", summary: "قيام ليالي رمضان والوتر." },
      ],
    },
    resources: {
      label: "موارد تطبيق الصلاة",
      title: "إجابات واضحة لاختيار تطبيق مواقيت الصلاة.",
      items: [
        { href: "/ar/ad-free-prayer-times-app/", title: "مواقيت بلا إعلانات", body: "لماذا يحافظ وقت الصلاة على تجربة هادئة ومركزة وخالية من الإعلانات." },
        { href: "/ar/salah-reminder-app/", title: "تذكيرات الصلاة", body: "كيف تساعدك التذكيرات على ترتيب يومك حول كل صلاة دون ضوضاء إضافية." },
        { href: "/ar/qibla-compass-app/", title: "بوصلة القبلة", body: "تجربة واضحة لمعرفة اتجاه القبلة على أندرويد بأقل ازدحام بصري." },
        { href: "/ar/prayer-times-widget-android/", title: "ويدجت مواقيت الصلاة", body: "ويدجت سهلة القراءة لمعرفة الصلاة القادمة من الشاشة الرئيسية." },
        { href: "/ar/how-prayer-times-are-calculated/", title: "حساب مواقيت الصلاة", body: "شرح واضح للموقع وطرق الحساب والمنطقة الزمنية والمعايرة." },
      ],
    },
    footer: {
      body: "صمم لمساعدة المسلمين على تنظيم يومهم حول الصلاة دون تشتيت أو إعلانات أو مزايا مقفلة.",
      seoBody: "وقت الصلاة تطبيق أندرويد مركز لمواقيت الصلاة وتذكيراتها واتجاه القبلة.",
      application: "التطبيق",
      features: "المزايا",
      about: "عن التطبيق",
      faq: "الأسئلة الشائعة",
      download: "التحميل لأندرويد",
      learn: "تعلّم",
      learnAbout: "تعلّم عن الصلاة",
      resources: "الموارد",
      legal: "القانوني",
      privacy: "سياسة الخصوصية",
      terms: "شروط الخدمة",
      methodology: "منهجية التحرير",
      contact: "التواصل والملاحظات",
      copyright: "وقت الصلاة. جميع الحقوق محفوظة.",
      closing: "وقت الصلاة مجاني بالكامل. زر الدعم داخل التطبيق اختياري ولا يلزم استخدامه.",
    },
  },
} as const;
